version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the frontend...
      - npm run build -- --configuration production
      - echo Build completed

  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync dist/front-end-angular/browser/ s3://${S3_BUCKET_NAME} --delete
      - echo Frontend deployed successfully

artifacts:
  files:
    - '**/*'
  base-directory: dist/front-end-angular/browser
