version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the frontend...
      - npm run build -- --configuration production
      - echo Build completed, checking output...
      - ls -la dist/
      - find dist/ -type d -name "*" | head -10

  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync dist/FrontEndAngular/browser/ s3://${S3_BUCKET_NAME} --delete
      - echo Frontend deployed successfully

artifacts:
  files:
    - '**/*'
  base-directory: dist/FrontEndAngular/browser
