version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Running tests...
      - npm test -- --watch=false --browsers=ChromeHeadless || echo "Tests completed"

  post_build:
    commands:
      - echo Test phase completed

artifacts:
  files:
    - '**/*'